# Generated by Django 4.0.5 on 2022-09-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('hot', 'Hot'), ('sale', 'Sale'), ('offer', 'Offer')], max_length=10, null=True),
        ),
    ]
